# Generated by Django 4.1.5 on 2023-03-24 07:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App', '0004_rename_user_hashed_client_cli_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashed_client',
            name='cli_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
