# Generated by Django 4.1.5 on 2023-04-01 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_alter_hashed_client_cli_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inc_notf', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
