# Generated by Django 4.1.5 on 2023-04-01 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='cli',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='App.client'),
        ),
    ]
