# Generated by Django 4.1.5 on 2023-04-02 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_notification_bks'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletMon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tot_amount', models.BigIntegerField(blank=True, null=True)),
                ('cli', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='App.client')),
            ],
        ),
    ]
