# Generated by Django 4.1.5 on 2023-04-02 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_walletmon'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='wallet',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.DeleteModel(
            name='WalletMon',
        ),
    ]
