# Generated by Django 4.1.5 on 2023-02-27 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(verbose_name='age')),
                ('sex', models.CharField(max_length=50, verbose_name='sex')),
                ('category_name', models.CharField(max_length=100, verbose_name='category_name')),
                ('surgery', models.CharField(max_length=200, verbose_name='surgery')),
                ('village', models.CharField(max_length=200, verbose_name='village')),
                ('district_name', models.CharField(max_length=200, verbose_name='district_name')),
                ('preauth_date', models.DateField(auto_now=True, verbose_name='preauth_date')),
                ('preauth_amt', models.IntegerField(verbose_name='preauth_amt')),
                ('claim_date', models.DateField(auto_now=True, verbose_name='claim_date')),
                ('claim_amount', models.IntegerField(verbose_name='claim_amount')),
                ('hosp_name', models.CharField(max_length=200, verbose_name='hosp_name')),
                ('hosp_type', models.CharField(max_length=50, verbose_name='hosp_type')),
                ('hosp_location', models.CharField(max_length=200, verbose_name='hosp_location')),
                ('hosp_district', models.CharField(max_length=200, verbose_name='hosp_district')),
                ('surgery_date', models.DateField(auto_now=True, verbose_name='surgery_date')),
            ],
        ),
    ]
