# Generated by Django 4.1.5 on 2023-03-25 05:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='category_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='claim_amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='claim_date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='district_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='hosp_district',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='hosp_location',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='hosp_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='hosp_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='preauth_amt',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='preauth_date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='sex',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='surgery',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='surgery_date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='village',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='hosp_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hosp_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=100)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
