# Generated by Django 4.1.5 on 2023-04-05 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_hospnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='hosp_details',
            name='wallet',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
