# Generated by Django 4.1.5 on 2023-04-05 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_hosp_details_wallet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hosp_details',
            old_name='wallet',
            new_name='hosp_wallet',
        ),
    ]
