# Generated by Django 4.1.5 on 2023-02-28 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Insurance', '0002_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankinsurance',
            name='policy_no',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
