# Generated by Django 4.1.5 on 2023-02-28 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Insurance', '0003_bankinsurance_policy_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankinsurance',
            name='policy_no',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
