# Generated by Django 4.1.5 on 2023-03-24 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Insurance', '0004_alter_bankinsurance_policy_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankinsurance',
            name='bank_name',
        ),
        migrations.AddField(
            model_name='bankinsurance',
            name='Bk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Insurance.bank'),
        ),
        migrations.AddField(
            model_name='bankinsurance',
            name='no_plans',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
