# Generated by Django 4.1.5 on 2023-03-26 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_alter_hashed_client_cli_user'),
        ('Insurance', '0006_alter_bankinsurance_no_plans'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill', models.FileField(default=None, max_length=250, null=True, upload_to='proof/')),
                ('doc_name', models.CharField(max_length=50)),
                ('hosp_name', models.CharField(max_length=50)),
                ('billing_date', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='InsDocs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proof', models.FileField(default=None, max_length=250, null=True, upload_to='proof/')),
                ('policy_no', models.CharField(max_length=200)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='App.client')),
            ],
        ),
    ]
