# Generated by Django 4.1.5 on 2023-03-26 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Insurance', '0007_billing_insdocs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankinsurance',
            name='coverage',
            field=models.CharField(choices=[('1', '₹2 Lac'), ('2', '₹3 Lac'), ('3', '₹5 Lac'), ('4', '₹10 Lac'), ('5', '₹25 Lac')], default=1, max_length=30),
        ),
    ]
