# Generated by Django 4.1.5 on 2023-03-26 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Insurance', '0008_alter_bankinsurance_coverage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankinsurance',
            old_name='policy_no',
            new_name='desc',
        ),
    ]
