# Generated by Django 4.1.5 on 2023-03-26 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Insurance', '0009_rename_policy_no_bankinsurance_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankinsurance',
            name='desc',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
