# Generated by Django 4.1.5 on 2023-03-27 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Insurance', '0011_rename_insdocs_userdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='client',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='Address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='City',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='NetWorth',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='Occupation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='State',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='firstname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='lastname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='ph_num',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='policy_no',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
