# Generated by Django 4.1.5 on 2023-03-27 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Insurance', '0012_remove_userdetails_client_userdetails_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='inc_proof',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='inc_proof/'),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='pic',
            field=models.ImageField(default=None, max_length=250, null=True, upload_to='user/'),
        ),
    ]
