# Generated by Django 4.1.5 on 2023-03-27 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Insurance', '0015_alter_userdetails_cli'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='cli',
        ),
    ]
