# Generated by Django 4.1.5 on 2023-03-27 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Insurance', '0016_remove_userdetails_cli'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='bill',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='bill/'),
        ),
    ]
