# Generated by Django 4.1.5 on 2023-03-29 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Insurance', '0018_userdetails_cli'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='banks',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Insurance.bank'),
        ),
    ]
