# Generated by Django 4.1.5 on 2023-03-30 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Insurance', '0020_remove_userdetails_address_remove_userdetails_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='bank_ins',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Insurance.bankinsurance'),
        ),
    ]
