# Generated by Django 4.1.5 on 2023-04-01 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Insurance', '0022_userdetails_date_userdetails_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Deny', 'Deny')], default=1, max_length=30),
        ),
    ]
