# Generated by Django 4.1.5 on 2023-04-02 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Insurance', '0026_billing_policy_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='rel_fund',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billing',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Denied', 'Denied')], default=1, max_length=30),
        ),
    ]
