# Generated by Django 4.1.5 on 2023-04-02 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Insurance', '0028_billing_ap_date_billing_ap_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='trans_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
