# Generated by Django 4.1.5 on 2023-04-02 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Insurance', '0029_billing_trans_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='rel_fund',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
