# Generated by Django 4.1.5 on 2023-04-02 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Insurance', '0031_billing_hosp'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='hosp_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Denied', 'Denied')], default=1, max_length=30),
        ),
    ]
