# Generated by Django 4.1.5 on 2023-04-05 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Insurance', '0033_billing_cl_date_billing_cl_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='medication',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='billing',
            name='treatment',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
